PRINTF_PATH = $(LIB_PATH)/printf/src

VPATH += $(PRINTF_PATH) $(PRINTF_PATH)/printf
SRC += $(PRINTF_PATH)/printf/printf.c
QUANTUM_SRC +=$(QUANTUM_DIR)/logging/print.c
OPT_DEFS += -DPRINTF_SUPPORT_DECIMAL_SPECIFIERS=0
OPT_DEFS += -DPRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS=0
OPT_DEFS += -DPRINTF_SUPPORT_LONG_LONG=0
OPT_DEFS += -DPRINTF_SUPPORT_WRITEBACK_SPECIFIER=0
